const actionTypes = {
  getProducts: "GET_PRODUCTS",
  getProduct: "GET_PRODUCT",
  initApp: "INIT_APP_SETTING",
  getShops: "GET_SHOPS",
  getOrders: "GET_ORDERS",
  selectOrder: "SELECT_ORDER",
  fetchOptions: "FETCH_OPTIONS",
  fetchAvaliableCategories: "FETCH_AVALIABLE_CATEGORIES",
  setNewProductCategory: "SET_NEW_PRODUCT_CATEGORY",
  setNewProductOptions: "SET_NEW_PRODUCT_OPTIONS",
  fetchSingleShop: "FETCH_SINGLE_SHOP",
  fetchSummary: "FETCH_SUMMARY",
  createNewCategory: "CREATE_NEW_CATEGORY",
  refreshNewProduct: "REFRESH_NEW_PRODUCT",
  selectCategory: "SELECT_CATEGORY",
  selectOption: "SELECT_OPTION",
  createNewOption: "CREATE_NEW_OPTION",
  updateOption: "UPDATE_OPTION",
  removeOption: "REMOVE_OPTION",
  searchProductByName: "SEARCH_PRODUCT_BY_NAME",
  updateOrder: "UPDATE_ORDER",
  setSelectedCategoryImage: "SET_SELECTED_CATEGORY_IMAGE",
  setStartDate: "SET_START_DATE",
  setEndDate: "SET_END_DATE",
  fetchReportDetails: "FETCH_REPORT_DETAILS",
  setReportCategory: "SET_REPORT_CATEGORY",
  fetchOrdersByStore: "FETCH_ORDERS_BY_STORE",
  setProductImage: "SET_PRODUCT_IMAGE",
  shopOpenDateChange: "SHOP_OPEN_DATE_CHANGE",
  fetchUsers: "FETCH_USERS",
  fetchSalesGroups: "FETCH_SALES_GROUPS",
  fetchSalesGroup: "FETCH_SALES_GROUP",
  setPeriod: "SET_PERIOD",
  fetchCustomer: "FETCH_CUSTOMER"
};

export default actionTypes;
